/** List-view lead fields — excludes heavy JSON (intake, checklist). */
export const EMPLOYEE_LEAD_LIST_SELECT = {
  id: true,
  title: true,
  firstName: true,
  lastName: true,
  email: true,
  address: true,
  addressLine1: true,
  addressLine2: true,
  addressLine3: true,
  addressLine4: true,
  postCode: true,
  phone: true,
  disposition: true,
  remarks: true,
  moveToAdvisor: true,
  assignedAdvisorId: true,
  closedSale: true,
  verifiedSale: true,
  paymentReceived: true,
  caseStatus: true,
  callbackAt: true,
  updatedAt: true,
} as const

export const ADVISOR_LEAD_LIST_SELECT = {
  id: true,
  firstName: true,
  lastName: true,
  email: true,
  addressLine1: true,
  addressLine2: true,
  addressLine3: true,
  addressLine4: true,
  phone: true,
  remarks: true,
  closedSale: true,
  verifiedSale: true,
  caseStatus: true,
  assignedCaseAssessorId: true,
  preSipAt: true,
  updatedAt: true,
  assignedTo: { select: { name: true } },
  _count: { select: { documents: true } },
} as const

export const CASE_ASSESSOR_LEAD_LIST_SELECT = {
  id: true,
  firstName: true,
  lastName: true,
  email: true,
  addressLine1: true,
  addressLine2: true,
  addressLine3: true,
  addressLine4: true,
  phone: true,
  caseStatus: true,
  preSipAt: true,
  remarks: true,
  updatedAt: true,
  assignedTo: { select: { name: true } },
  assignedAdvisor: { select: { name: true } },
  _count: { select: { documents: true } },
} as const

export const ADMIN_CASE_LIST_SELECT = {
  id: true,
  firstName: true,
  lastName: true,
  email: true,
  addressLine1: true,
  addressLine2: true,
  addressLine3: true,
  addressLine4: true,
  phone: true,
  caseStatus: true,
  preSipAt: true,
  updatedAt: true,
  assignedTo: { select: { name: true } },
  assignedAdvisor: { select: { name: true } },
  assignedCaseAssessor: { select: { name: true } },
} as const
